services:
  - type: web
    name: invoice-backend
    env: python
    buildCommand: |
      cd backend && 
      pip install -r requirements.txt && 
      python manage.py makemigrations invoices &&
      python manage.py migrate
    startCommand: cd backend && gunicorn core.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: invoice-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: core.settings
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,localhost"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://invoicesystem-sandy.vercel.app"

databases:
  - name: invoice-db
    ipAllowList: [] 