services:
  - type: web
    name: invoice-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: invoice-db
          property: connectionString

databases:
  - name: invoice-db
    ipAllowList: [] 